package com.kidmobile.csr.global;

public class ConstantCountry {
	public static String[][] Country_str = {
		{"AFG", "아프가니스탄", "AFGHANISTAN"},
		{"AHO", "네덜란드령 안틸레스", "NETHERLANDS ANTILLES"},
		{"ALB", "알바니아", "ALBANIA"},
		{"ALG", "알제리", "ALGERIA"},
		{"AND", "안도라", "ANDORRA"},
		{"ANG", "앙골라", "ANGOLA"},
		{"ANT", "앤티과바부다", "ANTIGUA AND BARBUDA"},
		{"ARG", "아르헨티나", "ARGENTINA"},
		{"ARM", "아르메니아", "ARMENIA"},
		{"ARU", "아루바", "ARUBA"},
		{"ASA", "미국령 사모아", "AMERICAN SAMOA"},
		{"AUS", "오스트레일리아", "AUSTRALIA"},
		{"AUT", "오스트리아", "AUSTRIA"},
		{"AZE", "아제르바이잔", "AZERBAIJAN"},
		{"BAH", "바하마", "BAHAMAS"},
		{"BAN", "방글라데시", "BANGLADESH"},
		{"BAR", "바베이도즈", "BARBADOS"},
		{"BDI", "부룬디", "BURUNDI"},
		{"BEL", "벨기에", "BELGIUM"},
		{"BEN", "베넹", "BENIN"},
		{"BER", "버뮤다", "BERMUDA"},
		{"BHU", "부탄", "BHUTAN"},
		{"BIH", "보스니아헤르체고비나", "BOSNIA AND HERZEGOWINA"},
		{"BIZ", "벨리즈", "BELIZE"},
		{"BLR", "벨라루스", "BELARUS"},
		{"BOL", "볼리비아", "BOLIVIA"},
		{"BOT", "보츠와나", "BOTSWANA"},
		{"BRA", "브라질", "BRAZIL"},
		{"BRN", "바레인", "BAHRAIN"},
		{"BRU", "브루나이", "BRUNEI"},
		{"BUL", "불가리아", "BULGARIA"},
		{"BUR", "부르키나파소", "BGRBURKINA FASO"},
		{"CAF", "중앙아프리카공화국", "CENTRAL AFRICAN REPUBLIC"},
		{"CAM", "캄보디아", "CAMBODIA"},
		{"CAN", "캐나다", "CANADA"},
		{"CAY", "케이먼 제도", "CAYMAN"},
		{"CGO", "콩고", "CONGO"},
		{"CHA", "차드", "CHAD"},
		{"CHI", "칠레", "CHILE"},
		{"CHN", "중국", "CHINA"},
		{"CIV", "코트디부아르", "COTE D'IVOIRE"},
		{"CMR", "카메룬", "CAMEROON"},
		{"COD", "콩고민주공화국", "CONGO", "THE DEMOCRATIC REPUBLIC OF THE"},
		{"COK", "쿡", "COOK"},
		{"COL", "콜롬비아", "COLOMBIA"},
		{"COM", "코모로", "COMOROS"},
		{"CPV", "케이프베르데", "CAPE VERDE"},
		{"CRC", "코스타리카", "COSTA RICA"},
		{"CRO", "크로아티아", "CROATIA"},
		{"CUB", "쿠바", "CUBA"},
		{"CYP", "키프러스", "CYPRUS"},
		{"CZE", "체코", "CZECH"},
		{"DEN", "덴마크", "DENMARK"},
		{"DJI", "지부티", "DJIBOUTI"},
		{"DMA", "도미니카 연방", "DOMINICA"},
		{"DOM", "도미니카 공화국", "DOMINICAN REPUBLIC"},
		{"ECU", "에콰도르", "ECUADOR"},
		{"EGY", "이집트", "EGYPT"},
		{"ERI", "에리트레아", "ERITREA"},
		{"ESA", "엘살바도르", "EL SALVADOR"},
		{"ESP", "스페인", "SPAIN"},
		{"EST", "에스토니아", "ESTONIA"},
		{"ETH", "에티오피아", "ETHIOPIA"},
		{"FIJ", "피지", "FIJI"},
		{"FIN", "핀란드", "FINLAND"},
		{"FRA", "프랑스", "FRANCE"},
		{"FSM", "미크로네시아", "MICRONESIA"},
		{"GAB", "가봉", "GABON"},
		{"GAM", "감비아", "GAMBIA"},
		{"GBR", "영국", "UNITED KINGDOM"},
		{"GBS", "기니비사우", "GUINEA-BISSAU"},
		{"GEO", "그루지아", "GEORGIA"},
		{"GEQ", "적도 기니", "EQUATORIAL GUINEA"},
		{"GER", "독일", "GERMANY"},
		{"GHA", "가나", "GHANA"},
		{"GRE", "그리스", "GREECE"},
		{"GRN", "그레나다", "GRENADA"},
		{"GUA", "과테말라", "GUATEMALA"},
		{"GUI", "기니", "GUINEA"},
		{"GUM", "괌", "GUAM"},
		{"GUY", "가이아나", "GUYANA"},
		{"HAI", "아이티", "HAITI"},
		{"HKG", "홍콩", "HONG KONG"},
		{"HON", "온두라스", "HONDURAS"},
		{"HUN", "헝가리", "HUNGARY"},
		{"INA", "인도네시아", "INDONESIA"},
		{"IND", "인도", "INDIA"},
		{"IRI", "이란", "IRAN"},
		{"IRL", "아일랜드", "IRELAND"},
		{"IRQ", "이라크", "IRAQ"},
		{"ISL", "아이슬란드", "ICELAND"},
		{"ISR", "이스라엘", "ISRAEL"},
		{"ISV", "미국령 버진", "VIRGIN(U.S.)"},
		{"ITA", "이탈리아", "ITALY"},
		{"IVB", "영국령 버진", "VIRGIN(BRITISH)"},
		{"JAM", "자메이카", "JAMAICA"},
		{"JOR", "요르단", "JORDAN"},
		{"JPN", "일본", "JAPAN"},
		{"KAZ", "카자흐스탄", "KAZAKHSTAN"},
		{"KEN", "케냐", "KENYA"},
		{"KGZ", "키르기즈스탄", "KYRGYZSTAN"},
		{"KOR", "대한민국", "KOREA"},
		{"KSA", "사우디아라비아", "SAUDI ARABIA"},
		{"KUW", "쿠웨이트", "KUWAIT"},
		{"LAO", "라오스", "LAOS"},
		{"LAT", "라트비아", "LATVIA"},
		{"LBA", "리비아", "LIBYA"},
		{"LBR", "라이베리아", "LIBERIA"},
		{"LCA", "세인트루시아", "SAINT LUCIA"},
		{"LES", "레소토", "LESOTHO"},
		{"LIB", "레바논", "LEBANON"},
		{"LIE", "리히텐슈타인", "LIECHTENSTEIN"},
		{"LTU", "리투아니아", "LITHUANIA"},
		{"LUX", "룩셈부르크", "LUXEMBOURG"},
		{"MAD", "마다가스카르", "MADAGASCAR"},
		{"MAR", "모로코", "MOROCCO"},
		{"MAS", "말레이시아", "MALAYSIA"},
		{"MAW", "말라위", "MALAWI"},
		{"MDA", "몰도바", "MOLDOVA"},
		{"MDV", "몰디브", "MALDIVES"},
		{"MEX", "멕시코", "MEXICO"},
		{"MGL", "몽골", "MONGOLIA"},
		{"MKD", "마케도니아", "MACEDONIA"},
		{"MLI", "말리", "MALI"},
		{"MLT", "몰타", "MALTA"},
		{"MON", "모나코", "MONACO"},
		{"MOZ", "모잠비크", "MOZAMBIQUE"},
		{"MRI", "모리셔스", "MAURITIUS"},
		{"MTN", "모리타니아", "MAURITANIA"},
		{"MYA", "미얀마", "MYANMAR"},
		{"NAM", "나미비아", "NAMIBIA"},
		{"NCA", "니카라과", "NICARAGUA"},
		{"NED", "네덜란드", "NETHERLANDS"},
		{"NEP", "네팔", "NEPAL"},
		{"NFK", "노퍽", "NORFOLK"},
		{"NGR", "나이지리아", "NIGERIA"},
		{"NIG", "니제르", "NIGER"},
		{"NOR", "노르웨이", "NORWAY"},
		{"NRU", "나우루", "NAURU"},
		{"NZL", "뉴질란드", "NEW ZEALAND"},
		{"OMA", "오만", "OMAN"},
		{"PAK", "파키스탄", "PAKISTAN"},
		{"PAN", "파나마", "PANAMA"},
		{"PAR", "파라과이", "PARAGUAY"},
		{"PER", "페루", "PERU"},
		{"PHI", "필리핀", "PHILIPPINES"},
		{"PLE", "팔레스타인", "PALESTINE"},
		{"PLW", "팔라우", "PALAU"},
		{"PNG", "파푸아뉴기니", "PAPUA NEW GUINEA"},
		{"POL", "폴란드", "POLAND"},
		{"POR", "포르투갈", "PORTUGAL"},
		{"PRK", "북한", "KOREA", "DEMOCRATIC PEOPLE'S REPUBLIC OF"},
		{"PUR", "푸에르토리코", "PUERTO RICO"},
		{"QAT", "카타르", "QATAR"},
		{"ROM", "루마니아", "ROMANIA"},
		{"RSA", "남아프리카공화국", "SOUTH AFRICA"},
		{"RUS", "러시아", "RUSSIA"},
		{"RWA", "르완다", "RWANDA"},
		{"SAM", "사모아", "SAMOA"},
		{"SEN", "세네갈", "SENEGAL"},
		{"SEY", "세이셸", "SEYCHELLES"},
		{"SIN", "싱가포르", "SINGAPORE"},
		{"SKN", "세인트 키츠 앤 네비스", "SAINT KITTS AND NEVIS"},
		{"SLE", "시에라리온", "SIERRA LEONE"},
		{"SLO", "슬로베니아", "SLOVENIA"},
		{"SMR", "산마리노", "SAN MARINO"},
		{"SOL", "솔로몬", "SOLOMON"},
		{"SOM", "소말리아", "SOMALIA"},
		{"SRI", "스리랑카", "SRI LANKA"},
		{"STP", "상투메프린시페", "SAO TOME AND PRINCIPE"},
		{"SUD", "수단", "SUDAN"},
		{"SUI", "스위스", "SWITZERLAND"},
		{"SUR", "수리남", "SURINAME"},
		{"SVK", "슬로바키아", "SLOVAKIA"},
		{"SWE", "스웨덴", "SWEDEN"},
		{"SWZ", "스와질랜드", "SWAZILAND"},
		{"SYR", "시리아", "SYRIA"},
		{"TAN", "탄자니아", "TANZANIA"},
		{"TGA", "통가", "TONGA"},
		{"THA", "타이", "THAILAND"},
		{"TJK", "타지키스탄", "TAJIKISTAN"},
		{"TKM", "투르크메니스탄", "TURKMENISTAN"},
		{"TOG", "토고", "TOGO"},
		{"TPE", "대만", "TAIWAN"},
		{"TRI", "트리니다드 토바고", "TRINIDAD AND TOBAGO"},
		{"TUN", "튀니지", "TUNISIA"},
		{"TUR", "터키", "TURKEY"},
		{"UAE", "아랍에미레이트", "UNITED ARAB EMIRATES"},
		{"UGA", "우간다", "UGANDA"},
		{"UKR", "우크라이나", "UKRAINE"},
		{"URU", "우루과이", "URUGUAY"},
		{"USA", "미국", "UNITED STATES"},
		{"UZB", "우즈베키스탄", "UZBEKISTAN"},
		{"VIN", "세인트빈센트그레나딘", "SAINT VINCENT AND THE GRENADINES"},
		{"VEN", "베네주엘라", "VENEZUELA"},
		{"VIE", "베트남", "VIET NAM"},
		{"VAN", "바누아투", "VANUATU"},
		{"YEM", "예멘", "YEMEN"},
		{"YUG", "유고슬라비아", "YUGOSLAVIA"},
		{"ZAM", "잠비아", "ZAMBIA"},
		{"ZIM", "짐바브웨", "ZIMBABWE"}
	};
}
